apiVersion: v1
kind: Service
metadata:
  name: sample-demo-app-k8s-svc
spec:
  selector:
    app: sample-demo-app-k8s-svc
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8083
  type: LoadBalancer